data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/key/airflow-dataonline-f820c1ad1312.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-dataonline'
    dataset: retail

